export const RegistrationErrorCodes = {
    PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
    PASSWORD_WEAK: "PASSWORD_WEAK",
    MISSING_FIELDS: "MISSING_FIELDS",
    DUPLICATE_USER: "DUPLICATE_USER",
    USERNAME_INVALID: "USERNAME_INVALID",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    TURNSTILE_VALIDATION_FAILED: "TURNSTILE_VALIDATION_FAILED",
};

export const CategoryErrorCodes = {
    INVALID_CHARACTERS: "INVALID_CHARACTERS",
};
