name: Deploy after tests pass

on:
    workflow_run:
        workflows: ["Run tests"]
        types: [completed]
        branches: [main]

permissions:
    contents: read
    id-token: write

concurrency:
    group: deploy-prod
    cancel-in-progress: true

env:
    NODE_VERSION: "22"
    AZURE_WEBAPP_NAME: joshspokemoncards

jobs:
    deploy:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main'
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - name: Checkout the exact commit that passed CI
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}
                  fetch-depth: 0

            - name: Azure login (OIDC)
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Ensure App Service app settings (Oryx + Node)
              uses: azure/cli@v2
              with:
                  inlineScript: |
                      az webapp config appsettings set \
                        --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                        --name ${{ env.AZURE_WEBAPP_NAME }} \
                        --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true WEBSITE_NODE_DEFAULT_VERSION=~${{ env.NODE_VERSION }} --output none

            - name: Stage deploy payload
              run: | 
                rm -rf deploy-src && mkdir deploy-src
                rsync -a . deploy-src \
                    --exclude '.git/' \
                    --exclude '.github/' \
                    --exclude '.vscode/' \
                    --exclude 'tests/' \
                    --exclude 'test-results/' \
                    --exclude 'playwright-report/' \
                    --exclude '**/.DS_Store' \
                    --exclude 'node_modules/' \
                    --exclude '**/node_modules/' \
                    --exclude '.env' \
                    --exclude '.env.*' \
                    --exclude 'app.zip' \
                    --exclude 'node_modules.tar.gz' \
                    --delete-excluded

            - name: Deploy to Azure Web App (Oryx build)
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                package: deploy-src
                clean: true
