name: Deploy after tests pass

on:
    workflow_run:
        workflows: ["Run tests"]
        types: [completed]
    workflow_dispatch: {}

permissions:
    contents: read
    id-token: write

concurrency:
    group: deploy-prod
    cancel-in-progress: true

env:
    NODE_VERSION: "22"

jobs:
    deploy:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main'
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - name: Checkout the exact commit that passed CI
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_commit.id }}
                  fetch-depth: 0

            - name: Build front-end
              working-directory: front-end
              run: |
                  npm ci
                  npm run generate

            # - name: Package backend for deploy
            #   run: |
            #       mkdir -p deploy
            #       rsync -a back-end/ deploy/ --exclude node_modules --exclude tests --exclude .git --exclude .github
            #       rm -rf deploy/public && mkdir -p deploy/public
            #       cp -R front-end/.output/public/* deploy/public/
            #       pushd deploy
            #       npm ci --omit=dev
            #       popd
            #       (cd deploy && zip -r ../app.zip .)
