name: Deploy after CI

on:
    workflow_run:
        workflows: ["Run tests"]
        types: [completed]
    workflow_dispatch: {}

permissions:
    contents: read
    id-token: write

concurrency:
    group: deploy-prod
    cancel-in-progress: true

env:
    NODE_VERSION: "22"

jobs:
    deploy:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main'
        runs-on: ubuntu-latest
        environment:
            name: production
        steps:
            - name: Checkout the exact commit that passed CI
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_commit.id }}
                  fetch-depth: 0
