name: Run tests

on:
    push: {}
    pull_request: {}

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: testdb
                    options: >-
                        --health-cmd="mysqladmin ping --silent"
                        --health-interval=10s
                        --health-timeout=5s
                        --health-retries=5
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install & run frontend tests
              run: |
                  npm install --prefix front-end
                  npm test --prefix front-end

            - name: Install & run backend tests
              run: |
                  npm install --prefix back-end
                  npm test --prefix back-end

            - name: Wait for MySQL to be ready
              run: |
                  until mysqladmin ping -h 127.0.0.1 -u root -proot --silent; do
                    echo "Waiting for database connection..."
                    sleep 3
                  done

            - name: Set up database schema
              run: |
                  mysql -h 127.0.0.1 -u root -proot testdb < back-end/database/DDL.sql
